import {Item, RiskLevelEnum} from './item';

export const ITEMS: Item[] = [
  { trackingNumber: 'NC220073064BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'MeurynVitoriaMachadoDeAndrade', description: 'FashionAccessories-HairAccessories-HairClips&HairPins', count: 1, weight: 0.01, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC224526967BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'V¨ªtorYudiShinohara', description: 'Hobbies&Collections-CollectibleItems-ActionFigurines', count: 1, weight: 0.042, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC226752379BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'RosanaAlves', description: 'Pets-PetClothing&Accessories-Hats', count: 1, weight: 0.026, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC219280930BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'INI Farms', consignee: 'Ree7', description: 'Bananas', count: 1, weight: 1.40, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: 'https://app.pandoraintelligence.com/champ/case/dfb15702-042b-4d59-9d00-31b2a19b1b3c', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC225922023BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'Barendsen', consignee: 'Barberhouse', description: 'Laptop', count: 1, weight: 0.966, riskLevel: RiskLevelEnum.Medium, riskAnalysisLink: 'https://app.pandoraintelligence.com/champ/case/1cb46d5b-0e9c-4ce9-bae4-5553aa3c850f', uld: 'HGH10000CZ'},
  { trackingNumber: 'NC226152595BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'Milkor Marketing', consignee: 'ChVK Wagner', description: 'Caps', count: 1, weight: 0.156, riskLevel: RiskLevelEnum.High, riskAnalysisLink: 'https://app.pandoraintelligence.com/champ/case/e859a16b-5e64-4a26-b7b7-8dfeddc58eb0', uld: 'HGH10000CZ'},
  { trackingNumber: 'NC223083542BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'RubianeInocencio', description: 'Beauty-BeautyTools-HairTools-Others', count: 1, weight: 0.058, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC224750786BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'LarissaSiqueiraPapal¨¦o', description: 'Beauty-Hand,Foot&NailCare-NailCare-ManicureTools&Devices', count: 1, weight: 0.082, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC216836848BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'ThaisTonsigTeixeiraPrette', description: 'Mom&Baby-Toys-Baby&ToddlerToys-BathToys', count: 1, weight: 0.128, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC226562026BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'CristianeVieiraDosSantos', description: 'Hobbies&Collections-CollectibleItems-IdolCollectibles', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC214470985BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'GiovannaTomaselliFidelis', description: 'Home&Living-Kitchenware-Sealers', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC227338296BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'RosileneMoreira', description: 'Stationery-Writing&Correction-Eraser&CorrectionSupplies', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC225086590BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'Helio', description: 'Home&Living-PartySupplies-PartyHats&Masks', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC222921338BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'MariaGabrieleAlvesMartinsDaSilva', description: 'FashionAccessories-AdditionalAccessories-Cufflinks', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC221456520BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'GuilherminaApMoraesTozzi', description: 'Home&Living-Bathrooms-Others', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC224072943BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'BrunaAlmeidaDias', description: 'Beauty-BeautyTools-MakeupAccessories-MakeupBrushes', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC220414965BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'MaxWilhiansRangelDeAlencar', description: 'Sports&Outdoors-Sports&OutdoorRecreationEquipments-Fishing-FishingRods&Reels', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC228530318BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'PriscilaAlvesAlmeida', description: 'WomenClothes-Socks&Stockings-Socks', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC226587734BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'KatherineWoytilla', description: 'FashionAccessories-Necklaces', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'},
  { trackingNumber: 'NC223843067BR', mawb: '145-10149591', carrier: 'CZ', origin: 'CAN', destination: 'GRU', consigner: 'CASSIESONG', consignee: 'AnaIzabelDeOliveira', description: 'Mom&Baby-Toys-Baby&ToddlerToys-Teethers', count: 1, weight: 1.0, riskLevel: RiskLevelEnum.Low, riskAnalysisLink: '', uld: 'LOW00001CZ'}
];
